import type { Metadata } from "next";
import '@/views/style/global.scss'
import { ProviderWrapper } from "@/shared/wrappers/provider-wrapper/ProviderWrapper";
import { Header } from "@/widgets/header/Header";
import { Footer } from "@/widgets/footer/Footer";
import { ScrollToTopButton } from "@/shared/scroll-to-top-button/ScrollToTopButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProviderWrapper>
        <body>
          <div>
            <Header />
            <div className="md:mt-[0px] mt-[-7px]">
              {children}
            </div>
          </div>
          <Footer />
          <ScrollToTopButton />
        </body>
      </ProviderWrapper>
    </html>
  );
}
